jdk:
  - oraclejdk8
before_install:
  - bin/init.sh
  - export SIREUM_HOME=.
  - unset JAVA_TOOL_OPTIONS
  - export SIREUM_NO_AOT=true
install:
  - rm -f lib/collections-*.jar lib/compiler-*.jar lib/jniutils-*.jar lib/nativeimage-*.jar lib/options-*.jar lib/truffle-compiler-*.jar lib/word-*.jar
  - bin/sireum slang run bin/build.cmd m2
  - rm -fR lib/cache
